CREATE USER 'iasst'@'localhost' IDENTIFIED BY '123456';

GRANT SELECT ON *.* TO 'iasst'@'localhost';

GRANT SELECT, INSERT, UPDATE, REFERENCES, DELETE, CREATE, DROP, ALTER, INDEX, TRIGGER, CREATE VIEW, SHOW VIEW, EXECUTE, ALTER ROUTINE, CREATE ROUTINE, CREATE TEMPORARY TABLES, LOCK TABLES, EVENT ON `iasst`.* TO 'iasst'@'localhost';

GRANT GRANT OPTION ON `iasst`.* TO 'iasst'@'localhost';